#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2020-present Fewtarius

echo "执行到scripts build_distro"
#bash -c 'read -n 1 -s -r'

#检查ARCH参数
echo "检查ARCH参数"
if [ !"${ARCH}" == true ]
then
  echo "export ARCH before building."
  exit 1
fi

#声明项目设备信息
echo "声明项目设备信息"
#export DISTRO=AmberELEC
export DISTRO=RetroPixel
export PROJECT=Rockchip

echo "Building ${DISTRO} for ${DEVICE}"

#如果没有这个文件夹就创建这个文件夹
echo "检查target文件夹是否存在"
if [ ! -d "target" ]
then
  mkdir target
fi

# Clean a few packages to ensure the build date and version are updated
#for package in amberelec emulationstation retroarch retrorun lib32 u-boot
#for package in linux

#清理下行声明的软件包，确保构建日期和版本已更新。
#for package in linux
#for package in u-boot
#do
#  ./scripts/clean ${package}
#done

echo "检查 ARCH 类型"
if [ "${ARCH}" == "aarch64" ]
then
	echo "即将执行 make image"
	#bash -c 'read -n 1 -s -r'
  make image
elif [ "${ARCH}" == "arm" ]
then
  # Only build the 32bit packages that we need rather than the whole image
  # to speed up the build process and save disk space.
  for package in build-lib32
  do
    scripts/build ${package}
    if [ ! $? == 0 ]
    then
      echo "Build failed..exiting."
      exit 1
    fi
  
    scripts/install ${package}
    if [ ! $? == 0 ]
    then
      echo "Build failed..exiting."
      exit 1
    fi
  done
fi

if [ ! $? == 0 ]
then
  echo "Build failed..exiting."
  exit 1
fi

echo "release 文件创建"
if [ "${ARCH}" == "aarch64" ]
then
  if [ -d "release/${ARCH}/RPPOCKET" ]
  then
    rm -rf "release/${ARCH}/RPPOCKET"
  fi
mkdir -p release/${ARCH}/RPPOCKET
mv target/* "release/${ARCH}/${DEVICE}/"
fi
