#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2010-2011 Roman Weber (roman@openelec.tv)
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

. config/options "${1}"

echo "Install scripts started"
echo "config/options:" ${1}
echo "PKG_NAME:" ${PKG_NAME}
echo "INSTALL:" ${INSTALL}
echo "PKG_ARCH:" ${PKG_ARCH}

#检查脚本的第一个参数是否为空。如果为空，就打印一条用法提示信息并退出脚本。
if [ -z "${1}" ]; then
  die "usage: ${0} package_name [parent_pkg]"
fi

#用于验证当前处理的包是否存在对应的 .mk 配置文件
if [ -z "${PKG_NAME}" ]; then
  die "$(print_color CLR_ERROR "${1}: no package.mk file found")"
fi

#检查环境变量 INSTALL 是否为空。如果为空，就打印一条错误信息，明确指出该脚本不应该被手动运行，然后强制退出
if [ -z "${INSTALL}" ] ; then
  die "error: '\${INSTALL}' not set! this script is not intended to be run manually"
fi

#包的架构兼容性检查
if [ -n "${PKG_ARCH}" ]; then
  listcontains "${PKG_ARCH}" "!${TARGET_ARCH}" && exit 0
  listcontains "${PKG_ARCH}" "${TARGET_ARCH}" || listcontains "${PKG_ARCH}" "any" || exit 0
fi

# set defaults
#从第一个命令行参数中解析出目标平台（TARGET）。
#如果没有指定目标平台，则提供一个默认值。
#设置父包名称（PARENT_PKG），用于构建系统中的依赖关系管理。
if [ "${1//:/}" != "${1}" ]; then
  TARGET="${1#*:}"
else
  TARGET=
fi
[ -z "${TARGET}" ] && TARGET="target"
PARENT_PKG="${2:-${PKG_NAME}:${TARGET}}"
echo "PARENT_PKG:" ${PARENT_PKG}

#为某个包的安装操作创建一个锁”，以实现进程间的同步，避免并发冲突
pkg_lock "${PKG_NAME}:${TARGET}" "install" "${PARENT_PKG}"

#检查一个包是否已经成功安装，如果已经安装，则直接跳过后续的安装步骤，以节省时间和确保构建过程的幂等性
#定义一个 “安装标记文件”（Stamp File）的路径。
#检查这个标记文件是否存在。
#如果文件存在，说明该包已安装，脚本解锁并立即退出。
#如果文件不存在，说明需要执行安装步骤，脚本继续往下执行。
STAMP=${STAMPS_INSTALL}/${PKG_NAME}/install_${TARGET}
if [ -f ${STAMP} ]; then
  pkg_lock_status "UNLOCK" "${PKG_NAME}:${TARGET}" "install" "already installed"
  echo "install finished"
  exit 0
fi

#安装阶段的核心逻辑，它负责协调包的编译、依赖安装和安装目录的准备。
if [ "${PARENT_PKG}" = "linux:target" ]; then
  echo "STAMPS_INSTALL" ${STAMPS_INSTALL}
  echo "PKG_NAME" ${PKG_NAME}
fi
#STAMPS_INSTALL /home/li/RK3326/AmberELEC/build.AmberELEC-RG351MP.aarch64/image/system
#PKG_NAME /home/li/RK3326/AmberELEC/build.AmberELEC-RG351MP.aarch64/image/.stamps
mkdir -p ${STAMPS_INSTALL}/${PKG_NAME}

#scripts/build linux linux:target
${SCRIPTS}/build "${1}" "${PARENT_PKG}"

if [ "${PARENT_PKG}" = "linux:target" ]; then
  echo "scripts/build linux linux:target finfish"
fi

if [ "${TARGET}" = "target" ] ; then
  for p in ${PKG_DEPENDS_TARGET}; do
    ${SCRIPTS}/install "${p}" "${PARENT_PKG}"
  done
elif [ "${TARGET}" = "init" ] ; then
  for p in ${PKG_DEPENDS_INIT}; do
    ${SCRIPTS}/install "${p}" "${PARENT_PKG}"
  done
  INSTALL=${BUILD}/initramfs
fi

if [ "${PARENT_PKG}" = "linux:target" ]; then
  echo "INSTALL=BUILD/initramfs finfish"
fi

pkg_lock_status "ACTIVE" "${PKG_NAME}:${TARGET}" "install"

build_msg "CLR_INSTALL" "INSTALL" "${PKG_NAME} $(print_color CLR_TARGET "(${TARGET})")" "indent"

mkdir -p ${INSTALL}

if [ "${PARENT_PKG}" = "linux:target" ]; then
  echo "PARENT_PKG is 'linux:target'."
  #read
else
    echo "PARENT_PKG is not 'linux:target'. It is '${PARENT_PKG}'."
fi

if [ "${TARGET}" = "target" ] ; then
  for PKG_TMP_DIR in ${PKG_DIR} \
                     ${PROJECT_DIR}/${PROJECT}/packages/${PKG_NAME} \
                     ${PROJECT_DIR}/${PROJECT}/devices/${DEVICE}/packages/${PKG_NAME} \
                     ; do

    [ -d ${PKG_TMP_DIR} ] || continue

    if [ -d ${PKG_TMP_DIR}/profile.d ]; then
      mkdir -p ${INSTALL}/etc/profile.d
      cp ${PKG_TMP_DIR}/profile.d/*.conf ${INSTALL}/etc/profile.d
    fi

    if [ -d ${PKG_TMP_DIR}/tmpfiles.d ]; then
      mkdir -p ${INSTALL}/usr/lib/tmpfiles.d
      cp ${PKG_TMP_DIR}/tmpfiles.d/*.conf ${INSTALL}/usr/lib/tmpfiles.d
    fi

    if [ -d ${PKG_TMP_DIR}/system.d ]; then
      mkdir -p ${INSTALL}/usr/lib/systemd/system
      cp -Pr ${PKG_TMP_DIR}/system.d/*.* ${INSTALL}/usr/lib/systemd/system
    fi

    if [ -d ${PKG_TMP_DIR}/udev.d ]; then
      mkdir -p ${INSTALL}/usr/lib/udev/rules.d
      cp ${PKG_TMP_DIR}/udev.d/*.rules ${INSTALL}/usr/lib/udev/rules.d
    fi

    if [ -d ${PKG_TMP_DIR}/hwdb.d ]; then
      mkdir -p ${INSTALL}/usr/lib/udev/hwdb.d
      cp ${PKG_TMP_DIR}/hwdb.d/*.hwdb ${INSTALL}/usr/lib/udev/hwdb.d
    fi

    if [ -d ${PKG_TMP_DIR}/sleep.d ]; then
      mkdir -p ${INSTALL}/usr/lib/systemd/system-sleep
      cp ${PKG_TMP_DIR}/sleep.d/* ${INSTALL}/usr/lib/systemd/system-sleep
    fi

    if [ -d ${PKG_TMP_DIR}/sleep.d.serial ]; then
      mkdir -p ${INSTALL}/usr/lib/systemd/system-sleep.serial
      cp ${PKG_TMP_DIR}/sleep.d.serial/* ${INSTALL}/usr/lib/systemd/system-sleep.serial
    fi

    if [ -d ${PKG_TMP_DIR}/sysctl.d ]; then
      mkdir -p ${INSTALL}/usr/lib/sysctl.d
      cp ${PKG_TMP_DIR}/sysctl.d/*.conf ${INSTALL}/usr/lib/sysctl.d
    fi

    if [ -d ${PKG_TMP_DIR}/modules-load.d ]; then
      mkdir -p ${INSTALL}/usr/lib/modules-load.d
      cp ${PKG_TMP_DIR}/modules-load.d/*.conf ${INSTALL}/usr/lib/modules-load.d
    fi

    if [ -d ${PKG_TMP_DIR}/sysconf.d ]; then
      mkdir -p ${INSTALL}/etc/sysconf.d
      cp ${PKG_TMP_DIR}/sysconf.d/*.conf ${INSTALL}/etc/sysconf.d
    fi

    if [ -d ${PKG_TMP_DIR}/debug.d ]; then
      mkdir -p ${INSTALL}/usr/share/debugconf
      cp ${PKG_TMP_DIR}/debug.d/*.conf ${INSTALL}/usr/share/debugconf
    fi

    if [ -d ${PKG_TMP_DIR}/modprobe.d ]; then
      mkdir -p ${INSTALL}/usr/lib/modprobe.d
      cp ${PKG_TMP_DIR}/modprobe.d/*.conf ${INSTALL}/usr/lib/modprobe.d
    fi
  done
fi

# install
if [ "${TARGET}" = "target" ] ; then
  pkg_call_exists pre_install && pkg_call pre_install
fi

if [ "${TARGET}" = "target" -a -d ${PKG_BUILD}/.install_pkg ]; then
  cp -PR ${PKG_BUILD}/.install_pkg/* ${INSTALL}
elif [ "${TARGET}" = "init" -a -d ${PKG_BUILD}/.install_init ]; then
  cp -PR ${PKG_BUILD}/.install_init/* ${INSTALL}
fi

if [ "${TARGET}" = "target" ] ; then
  pkg_call_exists post_install && pkg_call post_install
fi

touch ${STAMP}

pkg_lock_status "UNLOCK" "${PKG_NAME}:${TARGET}" "install" "installed"
